substitutions:
  name: "athom-relay-board-x2"
  friendly_name: "Athom Relay Board x2"
  project_name: "athom.relay-board-x2"
  project_version: "1.0"
  relay1_restore_mode: RESTORE_DEFAULT_OFF
  relay2_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp8285
  restore_from_flash: true

api:

ota:

logger:

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://athom-tech/athom-configs/athom-relay-board-x2.yaml

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

button:
  - platform: restart
    id: restart_button
    name: "${friendly_name} Restart"

switch:
  # Relay
  - platform: gpio
    name: "${friendly_name} - 1"
    pin: GPIO5
    id: relay1
    restore_mode: ${relay1_restore_mode}

  - platform: gpio
    name: "${friendly_name} - 2"
    pin: GPIO4
    id: relay2
    restore_mode: ${relay2_restore_mode}

light:
  - platform: status_led
    name: "${friendly_name} Status LED"
    disabled_by_default: true
    pin:
      inverted: true
      number: GPIO16

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      disabled_by_default: true
